### ISSUE TITLE
[Top Builder 2024]: Coracle

### ISSUE THREAD

**Issue by staab** [PlebLab/Top-Builder#21]
# 🏗️ Top Builder 2024 Application Form to track progress through Round 1 - 3 ~ Currently in Round 1

## 📝 Instructions
1. Only complete this form if you have been chosen for Top Builder, by PlebLab.
2. Provide detailed information to assist the judges in evaluating your project.

## 🧑‍🤝‍🧑 The Team
- **Team Name**: Coracle
- **Number of Founders**: 1
- **Team Background**:
   Jon has 13 years of experience in Web SaaS, including economic modeling, 3D printing, and small business software. Founded Coracle, and runs the Thank God for Nostr podcast. Daniele is a UI designer who has been involved with nostr since early on, and has been helping out with Coracle, Gossip, and other projects.
- **Bitcoin & Lightning Involvement**:
  I fell down the rabbit hole in late 2020 after listening to Breedlove on Pysh's podcast. I came at it from a libertarian/Austrian perspective, but quickly picked up a solid pleb-level technical understanding. I've been involved in nostr since before Dorsey discovered it, and have helped draft several NIPs. Coracle was one of the earlier clients in the space.
- **Origin Story**: 
  The censorship that happened on Twitter in October of 2020 opened my eyes. I set out to build a "sufficiently decentralized" social media protocol, ultimately getting on board with nostr in 2022. Since then I've focused in on building a Facebook Groups competitor, since the people I most want to serve are members of my local church community, and they generally use Facebook more than Twitter.

## 💡 The Idea
- **Project Overview**: Coracle is a general-purpose newbie-friendly nostr client.
- **Website**: info.coracle.social
- **GitHub**: https://github.com/coracle-social/coracle
- **Project Stage**: Software is beta-level. It's relatively complete, but requires a lot of refinement to reach maturity.
- **Supplementary Materials**:
  - [FUTO fellowship talk](https://www.youtube.com/watch?v=y4LjL3BhjbE)
  - [Nostrasia talk](https://www.youtube.com/watch?v=R-5DHymkfzw)
  - [Thank God for Nostr podcast](https://fountain.fm/show/vnmoRQQ50siLFRE8k061)
  - [(fairly old) Coracle Intro video](https://dufflepud.us-southeast-1.linodeobjects.com/coracle_intro.mp4)

## 📚 Additional Information
- **Additional Links/Info**:
  Received a grant last year from FUTO, current OpenSats grantee.

## 📌 Submission Type
- [ ] Initial Project Creation

## 🚀 Current Project Progress
- **Progress Made**: A ton of NIPs and features supported, including DMs, public and private groups, lists, feeds, WoT, content settings.
- **Challenges Faced**: Upgrading encryption is going to be a challenge. Creating private groups also has a lot of different failure modes.
- **Future Roadmap of what's next**: Fleshing out private groups, improving onboarding and login, exploring DVMs and relay proxies to improve performance without compromising on decentralization.

## ⏳ Round 1 Milestone
- **Keep in mind that completion will need to be by February 10th, 2024.**
- **First-round milestone the team has set for themselves:**
  - Edit/delete/status for calendar events and market listings
  - Add group activity notifications
  - Support new read status NIP
  - Re-work login, including support for OAuth-style nostr connect login
  - Write first version of "smart" relay proxy that handles NIP 65 transparently

## 📝 Submission Complete
- **All required information has been provided above.**

### Registration Opens: Monday, December 18, 2023
- **Application**: Interested teams apply for Top Builder.
- **Selection**: Teams will be chosen based on their application. See [FAQ](https://github.com/PlebLab/Top-Builder) for details.

### Round 1: January 13 - February 10, 2024
- **Workshops**: PlebLab weekly workshops start, available live and online.
- **Chat Access**: Selected teams join the PlebLab internal chat.
- **Mentorship**: Begins for teams.
- **Project Milestones**: Teams are set and judged on their first-round milestones.

### Round 2: February 10 - 24, 2024
- **Team Reduction**: PlebLab cuts half of the Top Builder teams. (Only half continued in Round 2.)
- **Project Milestones**: Teams are set and judged on their second-round milestones.
- **Workshops**: PlebLab weekly workshops continue.
- **Mentorship**: Continues.

### Round 3: Starting February 24, 2024
- **Team Reduction**: PlebLab narrows down to 6 Top Builder teams. (All will be pitching in Austin.)
- **Final Milestones**: Teams set final project milestones for the last round.
- **Preparation**: Teams prepare their pitch in front of judges. Final teams are contacted to come to Austin for Startup Day.

### Final Round at Startup Day: March 14, 2024
- **Preparation**: Teams work on their final pitches at PlebLab.
- **Presentations**: Final teams present before judges on Startup Day.
- **Deliberation**: Judges decide during a happy hour.
- **Announcement**: The winner of Top Builder is announced at Austin BitDevs.
- **Celebration**: After-party for Top Builder.

**Comment by staab** [comment]
# Version 0.4.1 released

[Changelog and announcement](https://njump.me/nevent1qythwumn8ghj7un9d3shjtnwdaehgu3wvfskuep0qy88wumn8ghj7mn0wvhxcmmv9uq32amnwvaz7tmjv4kxz7fwv3sk6atn9e5k7tcpr9mhxue69uhksmmyd33x7epwdehhxarjxyhxxmmd9uq3xamnwvaz7tmsw4e8qmr9wpskwtn9wvhsz8rhwden5te0vd58y6tnw3cxjmrv9ehx7um5wgcjucm0d5hsqg9h4929rpmkg0s3tsdmsy6ud7sh7nzpyfufpvjxw2l0dt9twx6g9ulvxtg2)

This was mostly a maintenance release, as lots of things continue to come up, although I did manage to check off items 1 and 3 of my milestone 1 goals.

One big shift in focus was back toward continued refinement of closed groups due to the interest of a potential pilot customer. This is the main stated goal of Coracle, so it's worthy of the attention I'm giving it. I'm in the midst of fixing several bugs related to relay selection and NIP 44 encryption support (or lack of it). I'm also exploring the creation of a new iteration of Coracle for the purpose of a white-labeled _multi-tenant_ deployment. Expect more on this next round.

**Comment by staab** [comment]
## Proxies considered harmful

Item number 5, "Write first version of "smart" relay proxy that handles NIP 65 transparently" was a stretch goal for this round. I started writing it using khatru (you can see my progress [here](https://github.com/coracle-social/smoxy)), but have abandoned the project due to some timely conversations, one of which you can find [here](https://github.com/nostr-protocol/nips/issues/1013).

The summary is that proxies have the ability to reduce bandwidth requirements, and implement some routing logic on behalf of clients, but they have two problems:

- The way to use a proxy that acts exactly like a relay would be to add it to a user's kind 10002 relay list. But if the proxy relies on this list to find relays to proxy, it would end up connecting to itself. Even if an implementation was set up to avoid connecting to itself, multiple proxies in a relay list would create an infinite proxy loop.
- Proxies by definition implement a man-in-the-middle role. Currently it's impossible to proxy AUTH, but if the protocol were changed (see https://github.com/nostr-protocol/nips/pull/1016 for a draft) a proxy would effectively be able to hijack a user's session, potentially exfiltrating private data from the target relay. Clients could still choose not to authenticate via proxy, but that brings us back to where we started.

**Comment by staab** [comment]
## Final Milestone 1 Update

I did manage to integrate NIP 46 this week, which took some doing and help from Pablo and Jeff, but it's done (sort of, the spec needs work and will likely change soon). I also re-designed the onboarding flow to put keys and relays in there place, and help people choose who to follow based on topical lists. I'm really happy with the result!

Here's a video summary of the whole milestone:

https://coracle.us-southeast-1.linodeobjects.com/coracle-topbuilder-1.mp4

**Comment by staab** [comment]
## Milestone 2 Goals

The focus this round will be on making Coracle work for platforms like Phantom Power Music, churches (which I have another pilot customer interested in), and small groups (like my local bitcoin meetup). The big part of this is implementing access controls on selected relays based on either an external data source (for platforms) or based on group membership. This will require a custom relay implementation. The other part of this is simplifying onboarding for new users through configurable membership auto-approvals and onboarding links with access control baked in.

In check-list form:

- [ ] Add FORCE_RELAYS option to Coracle which will be used instead of the gossip model to retrieve data
- [ ] Build a group-oriented relay
  - [ ] Enforce access controls based on group membership
  - [ ] Auto-approve membership requests based on policy
- [ ] Build a platform-oriented relay
  - [ ] Enforce access controls based on external policy
- [ ] Add group signup links that auto-join the group with claim.
- [ ] Add platform signup links that auto-join the relay with claim.
- [ ] Include default follows in invite links

Some other goals not directly related to the main work include:

- [ ] Update note styles to match @dtonon's mockups
- [ ] Re-write search select, which is buggy
- [ ] Improve [feed loading](https://github.com/coracle-social/coracle/issues/272)
- [ ] Add follow-all button for categories to onboarding
- [ ] Add new color palette and theme structure

You can see the full issue list [here](https://github.com/coracle-social/coracle/issues?q=is%3Aopen+is%3Aissue+milestone%3A0.4.3)

**Comment by staab** [comment]
## 2.1 Update

This week went great. I learned a chunk of Go so that I could hack on fiatjaf's khatru relay in order to create a relay that can enforce my custom auth policies. This includes simple relay admission, as well as NIP 87 group-based admission, in which the relay uses a member key to decrypt messages as they come in and keep the member list updated.

I also started working on invite links — the front-end is done, next week I'll add support to my custom relay to handle the invite codes to reduce the friction involved in joining a closed relay or group. I'll also draft a NIP to allow clients to send these claims using a new event kind.

Other things:

- I've added the option to add the "platform"'s pubkey to zap splits. This can be used with the main coracle instance to support development, or by a white-label provider to create a revenue model for them.
- While doing that, I added support for zap splits (not configuring them, just properly reading them).
- I fixed some bugs, including some related to feed loading and the search select.
- I added a follow-all button to the categories in onboarding.

Additionally, and not mentioned in my goals, I drafted a [NIP](https://github.com/nostr-protocol/nips/pull/1043) after a conversation with one of my pilot clients, who would like to find a way to get a feed of music in their instance of Coracle.

Next week I'll be finishing signup links, and doing design-related updates. I have contracted a local designer who is going to help me with the marketing copy. He'll have something to me by Friday, so the copy might not be completely done by then, but the ball is now rolling.

[Here's a quick demo of what I've gotten done.](https://coracle.us-southeast-1.linodeobjects.com/Screen Recording 2024-02-16 at 4.03.09 PM.mov)

**Comment by staab** [comment]
## 2.2 Update

This week I managed to check everything off my list, *and* demo the first ever Coracle "platform" deployment to a pilot customer. The way I'm approaching that is to rent a single VPS and set up multiple instances of coracle/triflector behind a single nginx reverse proxy.

A quick summary of what I did this week:

- Added signup links that users can create and configure, share, and accept. Relay and group invite codes are both supported.
- Added support for both group- and relay-based signup links to triflector.
- Applied Daniele's note design to the software, including a much better version of the WoT symbol.
- Started converting colors to the new theme, Daniele is helping me dial in where the new palette is used.
- Released version [0.4.3 of Coracle](https://coracle.social/nevent1qyfhwumn8ghj7mmxve3ksctfdch8qatz9uqsuamnwvaz7tmwdaejumr0dshszxthwden5te0dphkgmrzdajzumn0wd68yvfwvdhk6tcpypmhxue69uhhyetvv9uju6tyd9hk6tnrdaexzcmvv5h8gmm0d3ej7qg4waehxw309aex2mrp0yhxgctdw4eju6t09uqzphww6l5ucg7kjmahdd9fxlzwq46slv3usj0cs2w32qqvc8regs0r5hyh9p)
- Had a call with each of my pilot customers. Both projects seem ready to launch in the next couple of weeks!
- Worked with my web designer to come up with a first version of copy for Coracle's website. See below for a screenshot.

![Coracle Social](https://github.com/PlebLab/Top-Builder/assets/2494842/92b5e7d2-71c7-4593-bf31-34d33af4bcb8)

![Here's a quick demo of the progress this week](https://coracle.us-southeast-1.linodeobjects.com/tb2-2.mov)
